name: "Release"

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Check release name and tag
        env:
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          project_version="$(uv version --short --project .)"
          expected_release="v${project_version}"

          if [[ "$RELEASE_NAME" != "$expected_release" ]]; then
            echo "Release name '$RELEASE_NAME' does not match expected release '$expected_release'."
            exit 1
          fi

          if [[ "$RELEASE_TAG" != "$expected_release" ]]; then
            echo "Release tag '$RELEASE_TAG' does not match expected release '$expected_release'."
            exit 1
          fi

      - name: Build
        run: uv build

      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} dist/*.{whl,tar.gz} --clobber

      - name: Publish
        run: uv publish
